name: Auto Commit & Fix Errors

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  fix-errors:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install autopep8 black pylint

      # Auto fix F-strings issues using autopep8
      - name: Fix F-strings using autopep8
        run: |
          autopep8 --in-place --aggressive --aggressive .

      # Auto format the code using Black
      - name: Format code with Black
        run: |
          black .

      # Lint the code with pylint to ensure no further issues
      - name: Lint with pylint
        run: |
          pylint --disable=all --enable=F,E,W --max-line-length=120 .

      # Commit and push changes if there are any
      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Fix code style and errors"
          add: "."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
