name: Auto Commit & Fix Errors

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  fix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 autopep8 black

      - name: Run Auto Fix (autopep8)
        run: |
          autopep8 --in-place --aggressive --aggressive .

      - name: Run Black Formatter
        run: |
          black .

      - name: Run Flake8 Linter
        run: |
          flake8 . --max-line-length=79 --exclude=.git,__pycache__ --ignore=E501,F401,F403,F811

      - name: Commit & Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Fix code style issues"
          git push
