name: Python CLI Commit Action

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Configure Git identity
      run: |
        git config --global user.email "halwakk07@gmail.com"
        git config --global user.name "Hasnain Khan"

    - name: Run Python CLI for Commit
      run: |
        source venv/bin/activate
        python cli.py "Automated commit from GitHub Actions"
